"""Generate the ticket dataset for Project ATLAS.

The dataset has to satisfy one hard requirement: **the effects must be real, not
asserted.** It is easy to fabricate a table where SLA attainment happens to fall and
then "discover" why. That proves nothing, because the analysis is reading back the
author's intention rather than measuring anything.

So each planted effect is generated by its own mechanism:

- The **mix shift** is a monthly ramp in tier shares. Nothing about attainment is
  touched; the tiers simply have different SLA targets, so the same performance scores
  differently as the mix moves.
- The **backlog** is not a parameter. It emerges from a day-by-day priority queue
  simulation with finite capacity. The defect spike overloads the queue and the wait
  it creates persists after the spike ends, because tickets arriving later queue behind
  it. If the simulation were removed, this component would vanish.
- The **productivity gain** is a reduction in handle time only. It makes attainment
  better, in the same period the headline metric gets worse.
- The **definitional break** is not in the data at all. It is a choice of clock, applied
  to the current half only. The underlying tickets are unchanged.

Three clocks are recorded per ticket, which is what makes the decomposition possible:

    elapsed_hours = queue_wait + handle + pending_customer   (the strict clock)
    net_hours     = queue_wait + handle                      (the governed clock)
    work_hours    = handle                                   (counterfactual: no queue)

    python -m data.generate_tickets
"""

from __future__ import annotations

import datetime as dt
import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

CONFIG_PATH = Path(__file__).resolve().parent.parent / "config" / "scenario.yml"
OUTPUT_PATH = Path(__file__).resolve().parent / "tickets.parquet"


def load_config(path: Path | str | None = None) -> dict:
    path = Path(path) if path else CONFIG_PATH
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


@dataclass
class Calendar:
    """Month boundaries, so 'month 8 day 4' resolves to a real date."""

    start: dt.date
    months: int

    def month_start(self, month_index: int) -> dt.date:
        """month_index is 1-based."""
        year = self.start.year + (self.start.month - 1 + month_index - 1) // 12
        month = (self.start.month - 1 + month_index - 1) % 12 + 1
        return dt.date(year, month, 1)

    def month_days(self, month_index: int) -> int:
        this_month = self.month_start(month_index)
        next_month = self.month_start(month_index + 1)
        return (next_month - this_month).days

    def month_of(self, day: dt.date) -> int:
        return (day.year - self.start.year) * 12 + (day.month - self.start.month) + 1


def ramp(month_index: int, months: int, baseline_months: int,
         value_h1: float, value_h2: float) -> float:
    """Interpolate a share from its H1 level to its H2 level.

    A step change at the halfway point would make the mix shift trivially detectable
    and would not look like a real up-market push. The ramp starts partway through H1
    and completes before the end of H2, so the monthly series has to be read rather
    than eyeballed.
    """
    ramp_start = baseline_months - 2
    ramp_end = months - 2
    if month_index <= ramp_start:
        return value_h1
    if month_index >= ramp_end:
        return value_h2
    progress = (month_index - ramp_start) / (ramp_end - ramp_start)
    return value_h1 + (value_h2 - value_h1) * progress


def lognormal_hours(rng: np.random.Generator, median: float, sigma: float,
                    size: int) -> np.ndarray:
    """Lognormal with the given median. mu = ln(median) by definition."""
    return rng.lognormal(mean=math.log(median), sigma=sigma, size=size)


def build_arrivals(config: dict, rng: np.random.Generator,
                   calendar: Calendar) -> pd.DataFrame:
    """One row per ticket, with arrival timestamp, tier, category and handle time."""
    meta = config["meta"]
    demand = config["demand"]
    tiers = config["tiers"]
    categories = config["categories"]
    spike = config["defect_spike"]
    months = int(meta["months"])
    baseline_months = int(meta["baseline_months"])

    tier_names = list(tiers)
    category_names = [c["name"] for c in categories]
    category_weights = np.array([c["weight"] for c in categories], dtype=float)
    category_weights /= category_weights.sum()
    category_multiplier = {c["name"]: float(c["handle_multiplier"]) for c in categories}

    spike_start = calendar.month_start(int(spike["month"])) + dt.timedelta(days=3)
    spike_end = spike_start + dt.timedelta(days=int(spike["duration_days"]))
    spike_category_weight = next(
        c["weight"] for c in categories if c["name"] == spike["category"]
    )

    frames: list[pd.DataFrame] = []
    for month_index in range(1, months + 1):
        month_start = calendar.month_start(month_index)
        days_in_month = calendar.month_days(month_index)
        base = demand["tickets_first_month"] * (1 + demand["monthly_growth"]) ** (
            month_index - 1)

        shares = np.array([
            ramp(month_index, months, baseline_months,
                 tiers[name]["share_start"], tiers[name]["share_end"])
            for name in tier_names
        ])
        shares = shares / shares.sum()

        for day_offset in range(days_in_month):
            day = month_start + dt.timedelta(days=day_offset)
            # Weekday seasonality: support volume is materially lower at weekends.
            weekday_factor = 0.55 if day.weekday() >= 5 else 1.16
            expected = base / days_in_month * weekday_factor

            in_spike = spike_start <= day < spike_end
            count = rng.poisson(expected)
            if count == 0:
                continue

            tier = rng.choice(tier_names, size=count, p=shares)
            category = rng.choice(category_names, size=count, p=category_weights)

            if in_spike:
                # The regression generates extra tickets in ONE category, on top of
                # normal volume -- modelled as additional arrivals rather than as a
                # reweighting, because that is what a defect does.
                #
                # Scaled by the affected category's share: a 2.4x multiplier on a
                # category holding 19% of volume is +27% on the total, not +140%.
                # Getting this wrong made the spike large enough that the queue never
                # drained, which would have turned a transient into permanent
                # under-capacity and quietly validated the hypothesis the analysis is
                # meant to test.
                extra = rng.poisson(
                    expected * spike_category_weight
                    * (spike["volume_multiplier"] - 1.0)
                )
                if extra > 0:
                    tier = np.concatenate([tier, rng.choice(tier_names, size=extra, p=shares)])
                    category = np.concatenate(
                        [category, np.full(extra, spike["category"])])
                    count += extra

            # Intra-day arrival times, weighted toward working hours.
            hour = np.clip(rng.normal(13.5, 4.2, size=count), 0, 23.999)
            created = [
                dt.datetime.combine(day, dt.time(0)) + dt.timedelta(hours=float(h))
                for h in hour
            ]

            frames.append(pd.DataFrame({
                "created_at": created,
                "tier": tier,
                "category": category,
                "arrival_day": day,
                "month_index": month_index,
            }))

    tickets = pd.concat(frames, ignore_index=True)
    tickets = tickets.sort_values("created_at").reset_index(drop=True)
    tickets["ticket_id"] = np.arange(1, len(tickets) + 1)

    # Handle time: tier median x category multiplier, with the H2 productivity gain
    # and a new-hire penalty applied later.
    medians = tickets["tier"].map(lambda t: tiers[t]["handle_hours_median"]).to_numpy()
    sigmas = tickets["tier"].map(lambda t: tiers[t]["handle_hours_sigma"]).to_numpy()
    multipliers = tickets["category"].map(category_multiplier).to_numpy()

    raw = rng.lognormal(mean=np.log(medians), sigma=sigmas)
    tickets["handle_hours_base"] = raw * multipliers

    improvement = float(config["productivity"]["handle_time_improvement_h2"])
    is_h2 = tickets["month_index"] > baseline_months
    tickets["handle_hours"] = tickets["handle_hours_base"] * np.where(
        is_h2, 1.0 - improvement, 1.0)
    tickets["is_current_half"] = is_h2
    return tickets


def simulate_queue(config: dict, calendar: Calendar,
                   tickets: pd.DataFrame) -> pd.DataFrame:
    """Day-by-day priority queue with finite capacity.

    This is the part that has to be a simulation. Backlog is a *stock*: it is created
    by a period of over-demand and then drains slowly, so tickets that arrive well
    after the causing event still wait behind it. A parameter called
    'backlog_hours_h2' could not reproduce that, and the whole point of the analysis is
    that the damage outlives the event.

    Higher-tier tickets are served first, which is realistic and also makes the finding
    harder: enterprise tickets are *protected* by priority and still miss their target,
    because a 4-hour SLA leaves almost no room for queueing at all.

    Tickets **age up** the priority order the longer they wait. A first version used
    strict priority with no ageing, and the result was that standard-tier tickets were
    starved completely whenever a backlog existed -- they lost 35 percentage points of
    attainment to queue wait alone, which swamped every other component and is not how
    a real support organisation behaves. Every queue discipline worth modelling has some
    fairness mechanism; without one the simulation produces a pathology rather than a
    backlog.
    """
    tiers = config["tiers"]
    capacity_config = config["capacity"]
    months = int(config["meta"]["months"])

    priority = {name: int(spec["queue_priority"]) for name, spec in tiers.items()}

    agents_start = float(capacity_config["agents_first_month"])
    agents_final = float(capacity_config["agents_final_month"])
    per_agent = float(capacity_config["tickets_per_agent_per_day"])

    def agents_in_month(month_index: int) -> float:
        if months == 1:
            return agents_start
        progress = (month_index - 1) / (months - 1)
        return agents_start + (agents_final - agents_start) * progress

    # Group arrivals by day.
    by_day: dict[dt.date, list[tuple[int, int, dt.datetime, float]]] = {}
    for row in tickets.itertuples(index=False):
        by_day.setdefault(row.arrival_day, []).append(
            (priority[row.tier], row.ticket_id, row.created_at, row.handle_hours)
        )

    all_days = sorted(by_day)
    first_day, last_day = all_days[0], all_days[-1]

    ageing_days = float(capacity_config["priority_ageing_days"])

    # Waiting tickets: (base_priority, created_at, ticket_id).
    waiting: list[tuple[int, dt.datetime, int]] = []
    started_at: dict[int, dt.datetime] = {}
    backlog_by_day: dict[dt.date, int] = {}

    day = first_day
    # Run past the last arrival so the tail of the queue drains and every ticket
    # receives a start time.
    horizon = last_day + dt.timedelta(days=90)
    while day <= horizon:
        for prio, ticket_id, created_at, _handle in by_day.get(day, []):
            waiting.append((prio, created_at, ticket_id))

        weekday = day.weekday()
        month_index = min(max(calendar.month_of(day), 1), months)
        # Weekend cover is thinner, matching the demand pattern.
        available = agents_in_month(month_index) * (0.40 if weekday >= 5 else 1.12)
        capacity_today = int(available * per_agent)

        if waiting:
            shift_start = dt.datetime.combine(day, dt.time(9, 0))

            def sort_key(item: tuple[int, dt.datetime, int],
                         now: dt.datetime = shift_start) -> tuple[float, dt.datetime]:
                base_priority, created_at, _ = item
                days_waiting = max((now - created_at).total_seconds() / 86400.0, 0.0)
                # One priority step per `ageing_days` of waiting, floored at the top
                # priority so an aged standard ticket competes with a fresh enterprise one.
                effective = max(1.0, base_priority - days_waiting / ageing_days)
                return (effective, created_at)

            waiting.sort(key=sort_key)
            serve, waiting = waiting[:capacity_today], waiting[capacity_today:]
            for _prio, created_at, ticket_id in serve:
                # Work starts when an agent picks it up or when it arrived, whichever is
                # later. Within a day, service begins at 09:00 or on arrival.
                started_at[ticket_id] = max(shift_start, created_at)

        backlog_by_day[day] = len(waiting)
        day += dt.timedelta(days=1)

    if waiting:
        raise RuntimeError(
            f"{len(waiting)} tickets never started -- capacity is too low for the "
            f"simulation horizon, which would silently truncate the dataset"
        )

    starts = pd.Series(started_at, name="started_at")
    starts.index.name = "ticket_id"
    tickets = tickets.merge(starts, left_on="ticket_id", right_index=True, how="left")

    backlog = pd.Series(backlog_by_day, name="backlog_open_at_close")
    backlog.index.name = "arrival_day"
    tickets = tickets.merge(backlog, left_on="arrival_day", right_index=True, how="left")

    queue_wait = (tickets["started_at"] - tickets["created_at"])
    tickets["queue_wait_hours"] = queue_wait.dt.total_seconds() / 3600.0
    if (tickets["queue_wait_hours"] < 0).any():
        raise RuntimeError("negative queue wait -- the simulation is inconsistent")
    return tickets


def add_clocks_and_attributes(config: dict, rng: np.random.Generator,
                              tickets: pd.DataFrame) -> pd.DataFrame:
    """Pending-customer time, the three clocks, agent tenure and quality flags."""
    pending = config["pending_customer"]
    quality = config["quality"]
    agents = config["agents"]
    tiers = config["tiers"]
    baseline_months = int(config["meta"]["baseline_months"])
    count = len(tickets)

    is_h2 = tickets["is_current_half"].to_numpy()

    # -- agent tenure. Hiring through the year means more new agents in H2, so the
    # new-hire penalty is a genuine partial effect rather than a decoy.
    threshold = int(agents["new_hire_tenure_threshold"])
    new_hire_share = np.where(is_h2, 0.19, 0.13)
    is_new_hire = rng.random(count) < new_hire_share
    tenure = np.where(
        is_new_hire,
        rng.integers(1, threshold + 1, size=count),
        rng.integers(threshold + 1, 61, size=count),
    )
    tickets["agent_tenure_months"] = tenure
    tickets["agent_is_new_hire"] = is_new_hire
    tickets["handle_hours"] = tickets["handle_hours"] * np.where(
        is_new_hire, 1.0 + float(agents["new_hire_handle_penalty"]), 1.0)

    # -- pending-customer time: excluded from the governed clock by policy.
    has_pending = rng.random(count) < float(pending["probability"])
    pending_hours = lognormal_hours(
        rng, float(pending["hours_median"]), float(pending["hours_sigma"]), count)
    tickets["pending_customer_hours"] = np.where(has_pending, pending_hours, 0.0)

    # -- the three clocks -------------------------------------------------- #
    # work  = handle only            (counterfactual with no queueing)
    # net   = queue + handle         (the governed definition)
    # elapsed = queue + handle + pending  (the strict clock the new tool reports)
    tickets["work_hours"] = tickets["handle_hours"]
    tickets["net_hours"] = tickets["queue_wait_hours"] + tickets["handle_hours"]
    tickets["elapsed_hours"] = (
        tickets["net_hours"] + tickets["pending_customer_hours"])
    tickets["resolved_at"] = tickets["created_at"] + pd.to_timedelta(
        tickets["elapsed_hours"], unit="h")

    tickets["sla_target_hours"] = tickets["tier"].map(
        lambda t: float(tiers[t]["sla_target_hours"]))

    # -- quality signals. These are generated flat-to-slightly-improving on purpose:
    # the issue tree has to be closable, and a hypothesis is only eliminated if the
    # data can actually rule it out.
    def flag(rate: float, delta: float) -> np.ndarray:
        probability = np.where(is_h2, rate + delta, rate)
        return rng.random(count) < probability

    tickets["reopened"] = flag(
        float(quality["reopen_rate"]), float(quality["reopen_rate_h2_delta"]))
    tickets["escalated"] = flag(
        float(quality["escalation_rate"]), float(quality["escalation_rate_h2_delta"]))
    tickets["misrouted"] = flag(
        float(quality["misroute_rate"]), float(quality["misroute_rate_h2_delta"]))

    tickets["half"] = np.where(is_h2, "H2", "H1")
    tickets["baseline_months"] = baseline_months
    return tickets


def build(config: dict) -> pd.DataFrame:
    rng = np.random.default_rng(int(config["meta"]["seed"]))
    start = config["meta"]["start_month"]
    start = start if isinstance(start, dt.date) else dt.date.fromisoformat(str(start))
    calendar = Calendar(start=start, months=int(config["meta"]["months"]))

    tickets = build_arrivals(config, rng, calendar)
    tickets = simulate_queue(config, calendar, tickets)
    tickets = add_clocks_and_attributes(config, rng, tickets)

    columns = [
        "ticket_id", "created_at", "started_at", "resolved_at",
        "month_index", "half", "arrival_day",
        "tier", "category", "sla_target_hours",
        "queue_wait_hours", "handle_hours", "pending_customer_hours",
        "work_hours", "net_hours", "elapsed_hours",
        "agent_tenure_months", "agent_is_new_hire",
        "reopened", "escalated", "misrouted", "backlog_open_at_close",
    ]
    return tickets[columns].sort_values("ticket_id").reset_index(drop=True)


def main() -> int:
    config = load_config()
    tickets = build(config)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    tickets.to_parquet(OUTPUT_PATH, index=False)

    total = len(tickets)
    print(f"wrote {total:,} tickets to {OUTPUT_PATH.name}")
    print(f"  period            {tickets['created_at'].min():%Y-%m-%d} to "
          f"{tickets['created_at'].max():%Y-%m-%d}")
    for half in ("H1", "H2"):
        subset = tickets[tickets["half"] == half]
        print(f"  {half}  tickets {len(subset):>7,}   "
              f"median queue wait {subset['queue_wait_hours'].median():>6.2f}h   "
              f"median handle {subset['handle_hours'].median():>5.2f}h")
    shares = (tickets.groupby("half")["tier"]
              .value_counts(normalize=True).unstack().round(4))
    print("  tier mix by half:")
    print(shares.to_string().replace("\n", "\n    "))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
